### ISSUE TITLE
请问如何切换语言

### ISSUE THREAD

**Issue by kinaito** [xuejiansaber/XZPixivDownloader#1]
我翻了monkey里，貌似没找到切换工具栏语言的，虽然也看得懂，但是吓了一跳，以为是pixiv自己的UI，好久没发现

ps2：可以下载排行榜的图实在太棒啦
ps2：比pxer的体验和成功率好太多了

**Comment by xuejianxianzun** [comment]
pixiv底部右下角有切换语言的选项：
日本語 English 한국어 简体中文 繁體中文
然后这个脚本的语言是根据你的pixiv的语言自动切换的
谢谢亲的支持~
