### ISSUE TITLE
好像卡住了

### ISSUE THREAD

**Issue by thelastfantasy** [xuejiansaber/XZPixivDownloader#13]
https://www.pixiv.net/member_illust.php?id=2470188&p=6
加载页数选择1页，试了很多次都没法获取完毕

**Comment by thelastfantasy** [comment]
好吧，换新版Firefox的话没问题
Firefox 52.9.0 ESR的话有问题

**Comment by xuejianxianzun** [comment]
ok~ 其实最推荐 Chrome，因为 Firefox 我用的少，只是基本的兼容。
给 Firefox 做的浏览器扩展还被下架了，我也懒得再弄了。
