### ISSUE TITLE
这个脚本已经在用zip打包功能打包ugoira了吧？

### ISSUE THREAD

**Issue by thelastfantasy** [xuejiansaber/XZPixivDownloader#14]
那为何不干脆给批量下载功能也加个打包下载的选项呢？当然要加的话希望功能稍微完善点，比如是否包含ugoira，是否对多图illust单独打包之类的选项。

这个脚本我一直是用来获取批量地址然后用老版Firefox上的DownThemALL扩展来批量下载，不过随着脚本更新，在老版Firefox上是越来越难用了，获取图片地址的进度经常中途卡住。
但是我又实在是不想用脚本的批量下载功能（我这边新版Firefox会无限弹文件另存为窗口...），那不如折衷下，批量下载后打包成一个zip的话，就比较能接受一点。

**Comment by xuejianxianzun** [comment]
ugoira 不是打包的，是用 p 站动图的 zip 文件直接改后缀的。
这个下载器没有使用打包功能，因为网络不好的话下载可能会卡住，有时候文件体积也太大。
你说的抓取图片网址也卡住，主要原因是网络问题。
火狐的无限弹窗，你可以单个下载 jpg png 动图，每个类型下载一次，勾选不再询问，就行了。
还是 chrome 方便。
