### ISSUE TITLE
Perhaps we need such a function that pictures larger than a given value are not downloaded.

### ISSUE THREAD

**Issue by mcthp** [xuejiansaber/XZPixivDownloader#18]
RT.

**Comment by xuejianxianzun** [comment]
Hello! In response to this demand, I initiated a group vote, 1 person needs this feature, 19 people choose not to need this feature, so I did not intend to add this feature.
In general, a larger volume means a larger width and height, or a higher quality, so most people prefer to collect large volumes of pictures.
The largest image in Pixiv is "GIF", you can choose not to download "GIF". I am sorry for the normal picture.
Thank you for your comments!

**Comment by mcthp** [comment]
I just want to save limited data traffic.
All right then, thank you for your response.

发送自 Windows 10 版邮件应用

发件人: xuejianxianzun
发送时间: 2019年2月25日 9:48
收件人: xuejianxianzun/XZPixivDownloader
抄送: Mcthp; Author
主题: Re: [xuejianxianzun/XZPixivDownloader] Perhaps we need such afunction that pictures larger than a given value are not downloaded. (#18)

Hello! In response to this demand, I initiated a group vote, 1 person needs this feature, 19 people choose not to need this feature, so I did not intend to add this feature.
In general, a larger volume means a larger width and height, or a higher quality, so most people prefer to collect large volumes of pictures.
The largest image in Pixiv is "GIF", you can choose not to download "GIF". I am sorry for the normal picture.
Thank you for your comments!
