### ISSUE TITLE
为什么不能保存到单独创建的文件夹里？

### ISSUE THREAD

**Issue by hengyuanma** [xuejiansaber/XZPixivDownloader#19]
我之前下载单独某位画师的图片时，脚本/插件会在Chrome默认的下载路径里再创建一个“作者ID-作者昵称”的单独的文件夹，然后下载的图片都保存到这个文件夹里。
从上周开始我发现忽然变成所有下载图片直接保存在默认下载路径，而不是单独创建文件夹了。
请问这是怎么一回事？新的feature吗？？？😂
我并没有更改过任何设置，仅仅允许了Chrome、插件、脚本的常规更新而已……

**Comment by xuejianxianzun** [comment]
因为“文件命名规则”由原来两个输入框变成一个输入框了，需要手动加“/”来作为文件夹标识。
鼠标放在它左侧的问号“？”上会有提示的
