### ISSUE TITLE
请问如何设置保存的文件名为原名？

### ISSUE THREAD

**Issue by operav** [xuejiansaber/XZPixivDownloader#2]
我把设置文件命名规则栏中留空，但是还会自动添加{id}，下载后的文件名前会附带“id_”，如果是单图，还会把结尾“_p0”抹掉。
保存为原文件名可以有效的防止我右键时重复收图，以及与其他图片出现命名冲突的情况（偶尔发生）。
请问如何设置才能保存文件名为原文件名呢？谢谢。

**Comment by xuejianxianzun** [comment]
我现在增加了 use_original_name 选项，把它的值改为 true 可以实现这个效果。（在 tampermonkey 里编辑脚本并保存。默认是false，也就是继续用我现在的规则，所以每次更新后你需要手动改一下）

另外现在的命名规则，也是有原因的。
首先命名规则栏不能留空，否则下载下来就是没有文件名，只有后缀名的文件了。以前有人把它清空导致了这个问题，所以现在清空的话会自动填上{id}。
至于添加“id_”前缀，是因为命名规则里有其他选项，为了作区分，一些选项在前面会加上标识，表明这个字段是什么。比如用来区分id和uid：id_68906461_uid_1893126。（你也可以尝试下使用其他标识，比如 tags）
单图去掉 _p0 后缀，可以和多图区分开，因为多图可以设置为只下载第一张图，如果都是 _p0 后缀，就无法区分单图还是多图了。单图不带 _p0 后缀，就可以确定是单图了。
右键收图的话，我的习惯是右键保存的文件夹和工具下载的文件夹是不同的，所以没有想到你说的这个用途。
现在先用 use_original_name 这个选项吧。

ps：如果我想确定一张图片是不是下载过，我一般会用 everything 来搜一下图片 id ，看硬盘上是不是已经有这个 id 的图片了（你的方法需要保存在同一个文件夹里才会提示重复）。你也可以试试 everything 这个软件，日常使用很方便。

**Comment by operav** [comment]
是的，我都把二次元肥宅快乐图（误😂）保存在同一个文件夹。
因为收图的网站和种类很固定，所以在保存图片时可以直接筛掉重复的图片。
期待后续版本可以在下载设置界面调用原文件名命名规则。辛苦了。
