### ISSUE TITLE
为下载面板添加滚动条，高度太大挡住下方内容了

### ISSUE THREAD

**Issue by ZSkycat** [xuejiansaber/XZPixivDownloader#22]
只需给 .centerWrap 添加以下样式
```
    max-height: calc(94% - 50px);
    overflow: auto;
```

另外建议自定义 class 加上命名空间防止未来的冲突
以及建议 class 命名使用中划线的风格
例如 `xzpixiv-center-wrap`

**Comment by xuejianxianzun** [comment]
之前没有用 overflow 是因为嫌滚动条丑，所以在关闭按钮左侧做了个收起设置的按钮。
现在我把这个 css 也加上吧。命名风格懒得花时间去整理了，我现在更喜欢下划线（逃
