### ISSUE TITLE
功能请求，提供抓取作品停止条件

### ISSUE THREAD

**Issue by ZSkycat** [xuejiansaber/XZPixivDownloader#23]
比如抓取到第 N 张图后停止，或者抓取到某个 id 后停止。方便对某个画师进行的更新。

**Comment by xuejianxianzun** [comment]
抓取到第N张好说，你可以在列表页设置抓取几页，或者打开最新作品，设置抓取几个（更新了几个就抓取几个）。
抓取到某个 id，目前没打算做

**Comment by ZSkycat** [comment]
最新作品页面是指什么页面
