### ISSUE TITLE
P站更改了收藏栏的位置,帮你改了下脚本,亲测可用

### ISSUE THREAD

**Issue by yuzhan1990** [xuejiansaber/XZPixivDownloader#24]
今天发现你的脚本的快速收藏的星星不见了,就看了下,原来是本来路径的figure也改成div了,于是修改了下,从main开始查找,亲测可用,你拿去更新吧,代码如下:
	let toolbar; // 因为 p 站改版 class 经常变，所以从父元素查找，父元素的 class 变化没那么频繁. figure 元素
	let toolbar_parent = document.querySelectorAll('main > section');//改为从main开始查找 更新前为let toolbar_parent = document.querySelectorAll('figure>div');
	for (const el of toolbar_parent) {
		if (el.querySelector('div>section')) {
			toolbar = el.querySelector('div>section');
			break;
		}
	}
/*2019.06.06更新后收藏栏CSS路径 作者yuzhan1990
#root > div.sc-1nr368f-0.bBsgDe > div > div > main > section > div.sc-171jvz-0.hANaTy > figure > div.rsntqo-0.jQURdX > div > div.ye57th-1.fhMijy > section > div.sc-181ts2x-1.dTytBs
#root > div.sc-1nr368f-0.bBsgDe > div > div > main > section > div.sc-171jvz-0.hANaTy > div > div.rsntqo-0.jQURdX > div > div.ye57th-1.fhMijy > section > div.sc-181ts2x-1.dTytBs
*/

**Comment by xuejianxianzun** [comment]
我这几天改不了了，估计得等下周，谢谢你~


------------------
杳杳灵凤，绵绵长归。悠悠我思，永与愿违。万劫无期，何时来飞？


 




------------------ 原始邮件 ------------------
发件人: "yuzhan1990"<notifications@github.com>;
发送时间: 2019年6月6日(星期四) 下午3:23
收件人: "xuejianxianzun/XZPixivDownloader"<XZPixivDownloader@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [xuejianxianzun/XZPixivDownloader] P站更改了收藏栏的位置,帮你改了下脚本,亲测可用 (#24)




今天发现你的脚本的快速收藏的星星不见了,就看了下,原来是本来路径的figure也改成div了,于是修改了下,从main开始查找,亲测可用,你拿去更新吧,代码如下:
 let toolbar; // 因为 p 站改版 class 经常变，所以从父元素查找，父元素的 class 变化没那么频繁. figure 元素
 let toolbar_parent = document.querySelectorAll('main > section');//改为从main开始查找 更新前为let toolbar_parent = document.querySelectorAll('figure>div');
 for (const el of toolbar_parent) {
 if (el.querySelector('div>section')) {
 toolbar = el.querySelector('div>section');
 break;
 }
 }
 /*2019.06.06更新后收藏栏CSS路径 作者yuzhan1990
 #root > div.sc-1nr368f-0.bBsgDe > div > div > main > section > div.sc-171jvz-0.hANaTy > figure > div.rsntqo-0.jQURdX > div > div.ye57th-1.fhMijy > section > div.sc-181ts2x-1.dTytBs
 #root > div.sc-1nr368f-0.bBsgDe > div > div > main > section > div.sc-171jvz-0.hANaTy > div > div.rsntqo-0.jQURdX > div > div.ye57th-1.fhMijy > section > div.sc-181ts2x-1.dTytBs
 */

**Comment by xuejianxianzun** [comment]
马上更新，谢谢你！
