### ISSUE TITLE
火狐的扩展没了？

### ISSUE THREAD

**Issue by mo-han** [xuejiansaber/XZPixivDownloader#25]
API不支持了吗？

**Comment by xuejianxianzun** [comment]
因为提交第三方库的检查总是通不过，所以被下架了，我也懒得再弄。
把扩展版的文件打包然后自己签名一下，也是可以继续安装使用的。
你可以在火狐扩展商店里注册个账号，上传扩展，选择自用签名。

**Comment by mo-han** [comment]
等等，这个的扩展在哪？

**Comment by xuejianxianzun** [comment]
就是浏览器扩展呀
https://github.com/xuejianxianzun/PixivBatchDownloader
火狐的扩展确实被下架了。chrome 系浏览器可以在应用商店安装这个扩展，火狐需要自己拿去签名一下。

**Comment by mo-han** [comment]
稍等，我试一下本地载入
