### ISSUE TITLE
细节建议：批量下载收藏图片时能够选择倒序下载

### ISSUE THREAD

**Issue by ghost** [xuejiansaber/XZPixivDownloader#26]
这样的话，查看时按修改日期升序排列，看到的顺序就和收藏时间从旧到新一样了，方便查阅，后续手动保存图片时也不至于打乱顺序。

**Comment by xuejianxianzun** [comment]
按收藏时间查看吗，有点意思
不过我没有这个需求，懒得做啊……如果有人能提交 pull 我就省事了
这两天打算改下代码风格什么的，忙完了再说吧。

**Comment by xuejianxianzun** [comment]
不过要说的话，我还是觉得按收藏顺序查看图片这个需求很少人有啊。如果是要保存的话，你可以设置页数，只下载最近新增的那几页收藏。

**Comment by xuejianxianzun** [comment]
这个功能将很快于下一次更新加入。
