### ISSUE TITLE
Firefox Add-on Gone?

### ISSUE THREAD

**Issue by Yoposoc** [xuejiansaber/XZPixivDownloader#29]
The firefox Add-on version is gone.
The userscript is not working for me. 
Can I get the add-on?

**Comment by xuejianxianzun** [comment]
The Firefox plugin is no longer available. The new version now only supports chrome.
https://chrome.google.com/webstore/detail/pixiv-batch-downloader/hfgoikdmppghehigkckknikdgdcjbfpl
However, the new version of the submission was rejected, and the app store is still an old version.
Currently you can install the latest version offline from github.
https://github.com/xuejianxianzun/PixivBatchDownloader

**Comment by Yoposoc** [comment]
So currently, there is no way to get this plugin working for firefox?

**Comment by xuejianxianzun** [comment]
That's right
