### ISSUE TITLE
Yahello~~这里是Pxer的开发者

### ISSUE THREAD

**Issue by pea3nut** [xuejiansaber/XZPixivDownloader#3]
Yahello，我是[Pxer](https://github.com/pea3nut/Pxer)的开发者。

因为P站改版，Pxer又挂了。最近P站更新的差不多了，于是准备修理下Pxer时，发现了你的这个项目。

**我觉得开发的非常给力！几乎可以完全代替Pxer！！**

这种免费的开源软件，我觉得没必要弄2个，看了你的软件我有计划将Pxer彻底停止更新，并在[官方QQ群](https://jq.qq.com/?_wv=1027&k=46nvvs6)和[官方网站](http://pxer.pea3nut.org)跳转至你的项目。但是有以下几点担心：

1. 软件是否会在日后营利化，如按量收费、加广告、植入挖坑程序
1. 是否能够坚持维护

想知道作为作者的你对于以上2个问题的想法。

**Comment by xuejianxianzun** [comment]
谢谢你的夸奖，不胜荣幸 (*/ω＼*)

关于你的疑问：
1. 本工具永久免费，不会进行盈利（但接受捐赠）
2. 在可预见的未来，本工具可以及时的更新维护

如果从前代算起，本工具也有3年历史了，p站每次改版都会很快跟进。

最近我还在看能不能做成 Chrome 扩展，如果做成了，到时候就两个版本一起维护。

**Comment by xuejianxianzun** [comment]
Chrome 扩展已经发布了，简单的移植，不依赖脚本管理器了
https://chrome.google.com/webstore/detail/pixiv-batch-downloader/hfgoikdmppghehigkckknikdgdcjbfpl

**Comment by pea3nut** [comment]
可以尝试上架下[AMO](https://addons.mozilla.org/)~~免费的

**Comment by ChinaKevinLi** [comment]
我写了一个py的版本，基于pixivpy，换一下友链么？
:)
https://github.com/ChinaKevinLi/PixivURLs
