### ISSUE TITLE
180726 Pixiv更新后快速收藏功能出了点小问题

### ISSUE THREAD

**Issue by thelastfantasy** [xuejiansaber/XZPixivDownloader#4]
之前的快速收藏按钮的话，收藏成功后应该是把Pixiv的收藏按钮链接地址改成编辑地址，
不过现在的Pixiv把收藏按钮从超链接改成button按钮所以改超链接href属性的方式已经无效了。

另外本脚本的快速收藏逻辑是原样100%照搬illust自身标签吧，感觉这样的逻辑并不够完善，我之前也改过一个快速收藏的脚本，大概的逻辑是获取自己 https://www.pixiv.net/bookmark_tag_all.php 页面的所有标签，然后和illust自带标签对比，两数组取交集进行快速收藏，该脚本因为是修改Pixiv自带收藏按钮而非新建一个按钮所以经常会失效，最近我也懒得再继续跟着Pixiv继续更新了。不过这个脚本的逻辑感觉很好所以还是想给作者你推荐一下。 https://greasyfork.org/zh-CN/scripts/29069-ajax-pixiv-bookmark

另外Pixiv的动图ugoira的话，下载后的zip包后缀名改成.ugoira就可以直接用Honeyview图片查看器打开了，只是看图目的的话应该是能够满足绝大多数人的需求的。

**Comment by xuejianxianzun** [comment]
之前脚本没有修改 pixiv 收藏按钮的链接，只是在快速收藏成功后把它显示为红色。这次 pixiv 改版后，看来是把收藏按钮改成了不带 tag 的快速收藏，对脚本没有影响。

另外收藏 tag 取交集的话，是否不会增加新标签了？如果第一次收藏一个 fgo 的作品，之前自己的 tag 库里没有，就不添加 fgo 的标签了吗？我感觉不太恰当。

zip 改 ugoira 确实是个新发现，我也在用 honeyView，但是之前没发现这个功能，现在试了试，真方便啊，良心软件。这一点可以推广，唯一的问题在于 honeyView 的用户数量多不多，或者说没有安装 honeyView 的人是否愿意安装。目前我的想法是下版本把后缀改成 .ugoira，并在文件名里提示用 honeyView 打开。（写在 README 里很多人会看不到） 不知道这方面你有什么想法吗，谢谢 ♪(･ω･)ﾉ

**Comment by thelastfantasy** [comment]
影响还是有的，使用快速收藏后再点击变红了的心形收藏按钮，你会发现快速收藏添加的所有标签都被清空了（收藏还在就是标签全没了）


取交集还有个目的就是排除一些私人标签和一些废标签，Pixiv因为对普通用户有10个标签的限制，所以经常会出现"标签A/标签B/标签C"这样绕过限制的标签，这类基本上都是废标签，画师的话自己用可能无所谓，但是收藏着大量使用此类标签会让后期的收藏管理变得非常麻烦，个人标签总数也会急剧扩张。
我之前就是吃了这方面的亏，现在我的收藏页好几万标签，里面真正有用的大概只有几百个。很多标签都只对应1张图片，就再也起不到其他作用。


至于ugoira后缀名的问题，目前没有想到太好的办法，各个浏览器对这方面似乎都有相当多的限制，首先超链接的download属性应该是不行的，后缀名是自动添加的而且firefox里的download属性不支持跨域。blob + download 属性的话倒是不失为一个办法，可以参考 https://greasyfork.org/zh-CN/scripts/40098-twitter-image-download-mod
我个人用firefox esr + downthemall倒是本身就可以改后缀名

**Comment by xuejianxianzun** [comment]
收藏功能确实发生了冲突，下次更新把原本的收藏按钮隐藏，快速收藏和编辑收藏都由我添加的按钮来做。

tag 的话我仍然担心之前的问题，不能添加新标签的话很不好。虽然有时候我也会感觉添加了一些没用的标签，但是如果我们在搜索书签时，知道自己要找的是什么，知道标签名，那么这些废标签也只是多余而已，并没有害处。

下载用的一直是 blob + download，在 Chrome 上试了下 ugoira 后缀，很顺利。Firefox 上下午再测试测试吧，之前在 Firefox 上下载大量图片的话会有不太明显的内存泄漏，不知道新版 Firefox 上是否解决了。

**Comment by xuejianxianzun** [comment]
greasyfork 上已更新

**Comment by thelastfantasy** [comment]
辛苦了
