### ISSUE TITLE
过滤器不起作用

### ISSUE THREAD

**Issue by thelastfantasy** [xuejiansaber/XZPixivDownloader#5]
https://www.pixiv.net/member_illust.php?id=573302&type=ugoira
这里的 type=ugoira 完全没起作用

**Comment by xuejianxianzun** [comment]
看来是我最近在适配新版时，把这个忽略掉了。
因为在新版里没有“动图”作品列表了，动图合并到了“插画”列表里，上面的网址会被导航到“插画”列表里。
https://www.pixiv.net/member_illust.php?id=573302&type=illust
在旧版里 动图 和 插画 还是分开的，不过过一段时间会全部更新到新版。
稍后我修复一下，恢复这个功能。

**Comment by xuejianxianzun** [comment]
已更新，因为新版 api 不能直接获取动图列表，所以下载动图时需要先获取所有作品，过滤出动图。
