### ISSUE TITLE
新版用不习惯

### ISSUE THREAD

**Issue by thelastfantasy** [xuejiansaber/XZPixivDownloader#7]
新版只能直接下载吗，我用Downthemall下载，所以只要结果列表就行了，还是老版用着舒服点。

**Comment by thelastfantasy** [comment]
刚看了下，原来有取消直接下载的选项啊
因为我的pixiv是日文版的，所以脚本也是日文版的，改了脚本切到中文版才发现有取消快速下载的功能

不过...你日文版的翻译全是错的啊！！！

**Comment by thelastfantasy** [comment]
那么如果修复的话，希望
1. 修正日文版翻译
2. 通过cookies或者localstorage或者GM.setValue，记忆脚本的相关选项

**Comment by xuejianxianzun** [comment]
日语是机翻……望天
某些选项的记忆，之后可以做一下

**Comment by xuejianxianzun** [comment]
那个的日语翻译是错的，抱歉啊
和显示封面的一样的了，我先修改下

**Comment by xuejianxianzun** [comment]
选项的记忆里，以下3个选项我不打算记忆：
设置页面数量（不同类型的页面数量是变化的）
设置收藏数量（主要在 tag 搜索页用）
设置宽高条件（很少用到，记忆的话反而造成麻烦）

如果你方便的话可以加 qq 群 499873152，交流起来更方便~

**Comment by xuejianxianzun** [comment]
问题已解决
