### ISSUE TITLE
打个招呼

### ISSUE THREAD

**Issue by Mapaler** [xuejiansaber/XZPixivDownloader#8]
这么长时间不见，你的脚本模式又变了，现在是用浏览储存打包下载zip啊，我以前还想搞来着结果一看面向对象的编程就蒙了:sweat:。

要不要相互搞个友情链接什么的？

**Comment by xuejianxianzun** [comment]
没变呀，只有动图才下载zip……图片我还是单张下载的。
友链是指你的网站吗，我看了下挺有意思的，不过比较个人向，内容也少，就不做友链了
ε=ε=ε=逃

**Comment by Mapaler** [comment]
你单张下载的话，怎么下载到本地啊？我看又没有链接第三方下载工具，以为是e站下载脚本那样全部下载到储存然后打包zip提供出来。我在火狐没搞懂怎么用。

我是说的P站下载项目的友链拉，我的项目专做作者下载，所以需要按自定义搜索下载的应该就可以用你的。
这边我也希望吸引喜欢我的思路风格的用户过来。

**Comment by xuejianxianzun** [comment]
接收完图片数据，转换成 blob 对象，创建一个 blob url，然后设置 a 标签的 download 属性，最后点击 a 标签来下载。（扩展版是用的 chrome 的下载 api）

我去看了你的 wiki，还是觉得安装和配置比较麻烦。不过掩码和建立文件夹比较好，脚本版不能建立文件夹确实不方便（扩展版倒可以）。这个友链怎么加？

**Comment by Mapaler** [comment]
我最开始就是为了自己写的，最初是用DownThemAll!一张一张下累死，后来想起迅雷离线下载导出器这种才去自己研究Aria2写的。所以一开始就是面向有动手能力并且有较高自定义化需求的人的。再加上我现在身边的路由器都刷了OpenWrt，支持Aria2，所以我比较喜欢直接把下载链接发到路由器上去。
我有一个需求就是不要重复下载，并且保留文件的原始修改时间，用DownThemAll!的时候会直接跳过已有文件，并且会把文件修改为服务器时间，基本等同于上传时间，现在用的Aria2也是支持的，所以下载的文件的时间还有几年前的。

https://github.com/Mapaler/PixivUserBatchDownload/tree/dev5
我在开发分支做了个样子，在首页底下，你看这样行不行。你看我是放脚本还是放扩展，反正火狐似乎都不能工作，你不如只保留扩展版算了。

**Comment by xuejianxianzun** [comment]
我也是自己用的，最早用 ox163，但是没有它筛选条件，后来自己做了一个。不过我们从一开始的方向就不一样。

友链里放脚本吧，火狐也可以用的。不过新版本的提示文字不显示，火狐的 event 兼容问题头疼，明天看看修复下。

我的简介这样写吧：
- 支持多种页面里的批量下载，可以设置多种筛选条件
- 有一些辅助功能，如去除广告、快速收藏、看图模式等
- 下载不依赖第三方工具
- 支持多语言（机翻）

你的怎么写可以发给我，明天我加上~溜了溜了

**Comment by Mapaler** [comment]
刚才我试了一下你的脚本也没有任何反应啊，没看到有图片下载。

* 专做按作者下载，适合有专情画师的粉丝。
* 配合Aria2下载，可发送到本地或远端路由器。
* 可使用程序语言高度自定义保存文件夹、重命名。

你的我是先加到开发分支的，等两天我没发现Bug就并回去。

**Comment by xuejianxianzun** [comment]
你加 qq 群详聊吧

**Comment by KernelErr** [comment]
@xuejianxianzun @Mapaler 二位大大好，我编写了一个基于Python的类似工具，可以互挂友链么？[PixivSync](https://github.com/ChinaKevinLi/PixivSync)

**Comment by Mapaler** [comment]
@ChinaKevinLi 
我现在在老家没电脑，看了一下简介，你的脚本只输出链接，不负责下载吗？另外是否有下载某个画师id的作品的功能？
好像这个也是py的，你可以参考
https://nandaka.devnull.zone/2010/01/13/pixiv-batch-downloader/

**Comment by KernelErr** [comment]
@Mapaler 是的，下载原图只需要修改referer为P站的任意一个地址即可，我应该会在下一个版本更新下载的功能。自己平时是用Aria2来下载图片的，所以没考虑到这个问题。

**Comment by Mapaler** [comment]
@ChinaKevinLi 用Aria2下载也可以导出为Aria2的session格式，直接写好reffer，还可以定制下载重命名等。
