### ISSUE TITLE
报错了，应该是pixiv又更新了

### ISSUE THREAD

**Issue by thelastfantasy** [xuejiansaber/XZPixivDownloader#9]
测试URL： https://www.pixiv.net/member_illust.php?id=14000684
![b b o7x ey u _d 8hfi](https://user-images.githubusercontent.com/6077584/47954142-b6999200-dfc1-11e8-854a-baf04650f18e.png)

**Comment by xuejianxianzun** [comment]
修改代码造成了bug，昨天修复了。
